import { auth } from "@clerk/nextjs/server";
import { sql } from "@/app/lib/db";
import { ensureAdOwnership } from "@/app/lib/ad-security";
import { assertSameOrigin, readJsonObject, RequestError, textField } from "@/app/lib/request-security";
async function ensureProjectFields(){await ensureAdOwnership();await sql`ALTER TABLE ads ADD COLUMN IF NOT EXISTS project_name TEXT`;}
function validId(v:unknown){return (typeof v==="number"||typeof v==="string")&&/^[1-9]\d*$/.test(String(v))&&Number.isSafeInteger(Number(v));}
export async function POST(req:Request){const {userId}=await auth();if(!userId)return Response.json({error:"Unauthorized"},{status:401});try{assertSameOrigin(req);const i=await readJsonObject(req,65536);const projectName=textField(i,"projectName",120)||"Untitled campaign",brandName=textField(i,"brandName",200),product=textField(i,"product",200),audience=textField(i,"audience",500),benefit=textField(i,"benefit",1000),website=textField(i,"website",2048),tone=textField(i,"tone",50),adType=textField(i,"adType",50),generatedAds=textField(i,"generatedAds",50000),adCount=Number(i.adCount||5);if(!product||!generatedAds||!Number.isInteger(adCount)||adCount<1||adCount>20)throw new RequestError("Invalid project details.");await ensureProjectFields();const rows=await sql`INSERT INTO ads (clerk_user_id,project_name,brand_name,product,audience,benefit,website,tone,ad_type,ad_count,generated_ads) VALUES (${userId},${projectName},${brandName},${product},${audience},${benefit},${website},${tone},${adType},${adCount},${generatedAds}) RETURNING id,project_name`;return Response.json(rows[0]);}catch(e){return Response.json({error:e instanceof RequestError?e.message:"Could not save this project."},{status:e instanceof RequestError?e.status:503});}}
export async function PATCH(req:Request){const {userId}=await auth();if(!userId)return Response.json({error:"Unauthorized"},{status:401});try{assertSameOrigin(req);const i=await readJsonObject(req,65536);if(!validId(i.id))throw new RequestError("Invalid project id.");const projectName=textField(i,"projectName",120);if(!projectName)throw new RequestError("Project name is required.");await ensureProjectFields();let rows;if(typeof i.generatedAds==="string"){const brandName=textField(i,"brandName",200),product=textField(i,"product",200),audience=textField(i,"audience",500),benefit=textField(i,"benefit",1000),website=textField(i,"website",2048),tone=textField(i,"tone",50),adType=textField(i,"adType",50),generatedAds=textField(i,"generatedAds",50000),adCount=Number(i.adCount||5);if(!product||!generatedAds||!Number.isInteger(adCount)||adCount<1||adCount>20)throw new RequestError("Invalid project details.");rows=await sql`UPDATE ads SET project_name=${projectName},brand_name=${brandName},product=${product},audience=${audience},benefit=${benefit},website=${website},tone=${tone},ad_type=${adType},ad_count=${adCount},generated_ads=${generatedAds} WHERE id=${Number(i.id)} AND clerk_user_id=${userId} RETURNING id,project_name`;}else rows=await sql`UPDATE ads SET project_name=${projectName} WHERE id=${Number(i.id)} AND clerk_user_id=${userId} RETURNING id,project_name`;if(!rows.length)return Response.json({error:"Project not found."},{status:404});return Response.json(rows[0]);}catch(e){return Response.json({error:e instanceof RequestError?e.message:"Could not update this project."},{status:e instanceof RequestError?e.status:503});}}
export async function DELETE(req:Request){const {userId}=await auth();if(!userId)return Response.json({error:"Unauthorized"},{status:401});try{assertSameOrigin(req);const id=new URL(req.url).searchParams.get("id");if(!validId(id))throw new RequestError("Invalid project id.");await ensureProjectFields();const rows=await sql`DELETE FROM ads WHERE id=${Number(id)} AND clerk_user_id=${userId} RETURNING id`;if(!rows.length)return Response.json({error:"Project not found."},{status:404});return Response.json({success:true});}catch(e){return Response.json({error:e instanceof RequestError?e.message:"Could not delete this project."},{status:e instanceof RequestError?e.status:503});}}
